language: clojure
sudo: false
lein: lein

install:
  - sudo ./scripts/install-ci-deps /usr/local
  - lumo --version

script:
  - lein test-all
  - ./scripts/build
  - nvm install v6.4.0
  - node --version
  - node out/tests.js
  - lein test-lumo

branches:
  only:
    - master

jdk:
  - oraclejdk8
  - oraclejdk7

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
