= string.clj
:toc: left
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:

== Introduction

The missing clojurescript string manipulation library.

== Rationale

TODO

== Install

The simplest way to use _string.clj_ in a clojure project, is by including it in the dependency
vector on your *_project.clj_* file:

[source,clojure]
----
[string.clj "0.1.0-SNAPSHOT"]
----


== Quick start

.Import the namespace
[source, clojure]
----
(ns my.namespace
  (:require [string.core :as str]))
----

.Use its functions
[source, clojure]
----
(str/strip-tags "<p>just <b>some</b> text</p>")
;; => "just some text"

(str/strip-tags "<p>just <b>some</b> text</p>" "p")
;; => "just <b>some</b> text"
----

== Reference

[[contains]]
=== _contains?_

Determines whether a string contains a substring.

[source, clojure]
----
(str/contains? "foobar" "bar")
;; => true
----

[[startswith]]
=== _startswith?_

Check if the string starts with prefix.

[source, clojure]
----
(str/startswith? "foobar" "foo")
;; => true
----

[[endswith]]
=== _endswith?_

Check if the string ends with suffix.

[source, clojure]
----
(str/endswith? "foobar" "bar")
;; => true
----

[[empty]]
=== _empty?_

Check if the string is empty or contains only whitespaces.

[source, clojure]
----
(str/empty? "foobar")
;; => false

(str/empty? "   ")
;; => true
----

[[upper]]
=== _upper_

Converts string to all upper-case.

[source, clojure]
----
(str/upper "foobar")
;; => "FOOBAR"
----

[[lower]]
=== _lower_

Converts string to all lower-case.

[source, clojure]
----
(str/lower "FOO")
;; => "foo"
----

[[repeat]]
=== _repeat_

Repeats string N times.

[source, clojure]
----
(str/repeat "a" 3)
;; => "aaa"
----

[[trim]]
=== _trim_

Removes whitespace or specified characters from
both ends of string.

[source, clojure]
----
(str/trim " foo ")
;; => "foo"

(str/trim "-foo-", "-")
;; => "foo"
----

[[ltrim]]
=== _ltrim_

Removes whitespace or specified characters from
left side of string.

[source, clojure]
----
(str/ltrim " foo ")
;; => "foo "

(str/ltrim "-foo-", "-")
;; => "foo-"
----

[[rtrim]]
=== _rtrim_

Removes whitespace or specified characters from
right side of string.

[source, clojure]
----
(str/rtrim " foo ")
;; => " foo"

(str/rtrim "-foo-", "-")
;; => "-foo"
----

[[prune]]
=== _prune_

Truncates a string to certain left and adds "..." if necesary. Making
sure that the pruned string does not exceed the original length and avoid
half-chopped words when truncating.

[source, clojure]
----
(str/prune "Hello World" 5)
;; => "Hello..."

(str/prune "Hello World" 8)
;; => "Hello..."

(str/prune "Hello World" 11 " (...)")
;; => "Hello (...)"
----

[[join]]
=== _join_

Join strings together with given separator.

[source, clojure]
----
(str/join ["foo" "bar"])
;; => "foobar"

(str/join "," ["foo" "bar"])
;; => "foo,bar"
----

[[surround]]
=== _surround_

Surround a string with another string.

[source, clojure]
----
(str/surround "a" "-")
;; => "-a-"
----

[[quote]]
=== _quote_

Quote a string.

[source, clojure]
----
(str/quote "a")
;; => "\"a\""
----

[[unquote]]
=== _unquote_

Unquote a string.

[source, clojure]
----
(str/unquote "\"a\"")
;; => "a"
----

[[slugify]]
=== _slugify_

Transforms string into URL slug.

[source, clojure]
----
(str/slugify "Un éléphant à l'orée du bois")
;; => "un-elephant-a-loree-du-bois"
----

[[strip-tags]]
=== _strip-tags_

Remove html tags from string.

[source, clojure]
----
(str/strip-tags "<p>just <b>some</b> text</p>")
;; => "just some text"

(str/strip-tags "<p>just <b>some</b> text</p>" "p")
;; => "just <b>some</b> text"
----

[[parse-number]]
=== _parse-number_

General purpose function for parse number like strings to number. It
works with integers and floats.

[source, clojure]
----
(str/parse-number "1.4")
;; => 1

(str/parse-number "1.4" 1)
;; => 1.4

(str/parse-number "1" 2)
;; => 1

(str/parse-number "")
;; => NaN
----

[[parse-float]]
=== _parse-float_

Returns a float value. Wraps parseFloat.

[source, clojure]
----
(str/parse-float "1.4")
;; => 1.4

(str/parse-float "1")
;; => 1.0
----

[[parse-int]]
=== _parse-int_

Returns a number value in integer form. Wraps parseInt.

[source, clojure]
----
(str/parse-int "1.4")
;; => 1
----

[[format]]
=== _format_

Simple string interpolation.

[source, clojure]
----
(str/format "hello %s" "yen")
;; => "hello yen"

(str/format "hello %(name)s" {:name "yen"})
;; => "hello yen"
----

[[pad]]
=== _pad_

Pads the str with characters until the total string length is equal to
the passed length parameter.

By default, pads on the left with the space char.

[source, clojure]
----
(str/pad "1" {:length 8})
;; => "       1"

(str/pad "1" {:length 8 :padding "0"})
;; => "00000001"

(str/pad "1" {:length 8 :padding "0" :type :right})
;; => "10000000"

(str/pad "1" {:length 8 :padding "0" :type :both})
;; => "00001000"
----

[[caputalize]]
=== _capitalize_

Simple string interpolation.

[source, clojure]
----
(str/format "hello %s" "yen")
;; => "hello yen"

(str/format "hello %(name)s" {:name "yen"})
;; => "hello yen"
----
