= cuerdas
:toc: left
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:

== Introduction

The missing clojurescript string manipulation library.

[quote, Federico García Lorca, Las Seis Cuerdas]
____
La guitarra, +
hace llorar a los sueños. +
El sollozo de las almas +
perdidas, +
se escapa por su boca +
redonda. +
Y como la tarántula +
teje una gran estrella +
para cazar suspiros, +
que flotan en su negro +
aljibe de madera.
____


== Install

The simplest way to use _cuerdas_ in a clojure project, is by including it in the dependency
vector on your *_project.clj_* file:

[source,clojure]
----
[cuerdas "0.1.0-SNAPSHOT"]
----


== Quick start

.Import the namespace
[source, clojure]
----
(ns my.namespace
  (:require [cuerdas.core :as str]))
----

.Use its functions
[source, clojure]
----
(str/strip-tags "<p>just <b>some</b> text</p>")
;; => "just some text"

(str/strip-tags "<p>just <b>some</b> text</p>" "p")
;; => "just <b>some</b> text"
----


== Reference

[[contains]]
=== _contains?_

Determines whether a string contains a substring.

[source, clojure]
----
(str/contains? "foobar" "bar")
;; => true
----

[small]#Implemented in: *cljs*, *clj*#


[[startswith]]
=== _startswith?_

Check if the string starts with prefix.

[source, clojure]
----
(str/startswith? "foobar" "foo")
;; => true
----

[small]#Implemented in: *cljs*, *clj*#


[[endswith]]
=== _endswith?_

Check if the string ends with suffix.

[source, clojure]
----
(str/endswith? "foobar" "bar")
;; => true
----

[small]#Implemented in: *cljs*, *clj*#


[[empty]]
=== _empty?_

Check if the string is empty.

[source, clojure]
----
(str/empty? "foobar")
;; => false

(str/empty? "")
;; => true

(str/empty? " ")
;; => false
----

[small]#Implemented in: *cljs*, *clj*#


[[blank]]
=== _blank?_

Check if the string is empty or contains only whitespaces.

[source, clojure]
----
(str/empty? "foobar")
;; => false

(str/empty? "   ")
;; => true
----

[small]#Implemented in: *cljs*, *clj*#


[[upper]]
=== _upper_

Converts string to all upper-case.

[source, clojure]
----
(str/upper "foobar")
;; => "FOOBAR"
----

[small]#Implemented in: *cljs*, *clj*#


[[lower]]
=== _lower_

Converts string to all lower-case.

[source, clojure]
----
(str/lower "FOO")
;; => "foo"
----

[small]#Implemented in: *cljs*, *clj*#


[[repeat]]
=== _repeat_

Repeats string N times.

[source, clojure]
----
(str/repeat "a" 3)
;; => "aaa"
----

[small]#Implemented in: *cljs*, *clj*#


[[trim]]
=== _trim_

Removes whitespace or specified characters from
both ends of string.

[source, clojure]
----
(str/trim " foo ")
;; => "foo"

(str/trim "-foo-", "-")
;; => "foo"
----

[small]#Implemented in: *cljs*, *clj*#


[[ltrim]]
=== _ltrim_

Removes whitespace or specified characters from
left side of string.

[source, clojure]
----
(str/ltrim " foo ")
;; => "foo "

(str/ltrim "-foo-", "-")
;; => "foo-"
----

[small]#Implemented in: *cljs*, *clj*#


[[rtrim]]
=== _rtrim_

Removes whitespace or specified characters from
right side of string.

[source, clojure]
----
(str/rtrim " foo ")
;; => " foo"

(str/rtrim "-foo-", "-")
;; => "-foo"
----

[small]#Implemented in: *cljs*, *clj*#


[[prune]]
=== _prune_

Truncates a string to certain left and adds "..." if necesary. Making
sure that the pruned string does not exceed the original length and avoid
half-chopped words when truncating.

[source, clojure]
----
(str/prune "Hello World" 5)
;; => "Hello..."

(str/prune "Hello World" 8)
;; => "Hello..."

(str/prune "Hello World" 11 " (...)")
;; => "Hello (...)"
----

[small]#Implemented in: *cljs*, *clj*#


[[join]]
=== _join_

Join strings together with given separator.

[source, clojure]
----
(str/join ["foo" "bar"])
;; => "foobar"

(str/join "," ["foo" "bar"])
;; => "foo,bar"
----

[small]#Implemented in: *cljs*#


[[split]]
=== _split_

Splits a string on a separator a limited number of times.
The separator can be a string or RegExp instance.

[source, clojure]
----
(str/split "1 2 3")
;; => ["1" "2" "3"]

(str/split "1 2 3" " ")
;; => ["1" "2" "3"])

(str/split "1 2 3" #"\s")
;; => ["1" "2" "3"]

(str/split "1 2 3" #"\s" 2)
;; => ["1" "2 3"]
----

[small]#Implemented in: *cljs*, *clj*#


[[reverse]]
=== _reverse_

Return strign reverted

[source, clojure]
----
(str/reverse "bar")
;; => "rab"
----

[small]#Implemented in: *cljs*, *clj*#



[[chars]]
=== _chars_

Returns a seq of char strings from string.

[source, clojure]
----
(str/chars "bar")
;; => ["b" "a" "r"]
----

[small]#Implemented in: *cljs*, *clj*#


[[lines]]
=== _lines_

Return a list of the lines in the string.

[source, clojure]
----
(str/lines "foo\nbar")
;; => ["foo" "bar"]
----

[small]#Implemented in: *cljs*, *clj*#


[[slice]]
=== _slice_

Extracts a section of a string and returns a new string.

[source, clojure]
----
(str/slice "123" 1)
;; => "23"

(str/slice "1234" 1 3)
;; => "23"
----

[small]#Implemented in: *cljs*, *clj*#


[[replace]]
=== _replace_

Replaces all instance of match with replacement in s.

[source, clojure]
----
(str/replace "aa bb aa" "aa" "kk")
;; => "kk bb kk"

(str/replace "aa bb aa" #"aa" "kk")
;; => "kk bb kk"
----

[small]#Implemented in: *cljs*, *clj*#


[[replace-first]]
=== _replace-first_

Replaces first instance of match with replacement in s.

[source, clojure]
----
(str/replace-first "aa bb aa" "aa" "kk")
;; => "kk bb aa"

(str/replace-first "aa bb aa" #"aa" "kk")
;; => "kk bb aa"

(str/replace-first "aa bb aa" (str/regexp #"aa" "g") "kk")
;; => "kk bb aa"
----

[small]#Implemented in: *cljs*, *clj*#


[[surround]]
=== _surround_

Surround a string with another string.

[source, clojure]
----
(str/surround "a" "-")
;; => "-a-"
----

[small]#Implemented in: *cljs*#


[[quote]]
=== _quote_

Quote a string.

[source, clojure]
----
(str/quote "a")
;; => "\"a\""
----

[small]#Implemented in: *cljs*#


[[unquote]]
=== _unquote_

Unquote a string.

[source, clojure]
----
(str/unquote "\"a\"")
;; => "a"
----

[small]#Implemented in: *cljs*#


[[slugify]]
=== _slugify_

Transforms string into URL slug.

[source, clojure]
----
(str/slugify "Un éléphant à l'orée du bois")
;; => "un-elephant-a-loree-du-bois"
----

[small]#Implemented in: *cljs*#


[[strip-tags]]
=== _strip-tags_

Remove html tags from string.

[source, clojure]
----
(str/strip-tags "<p>just <b>some</b> text</p>")
;; => "just some text"

(str/strip-tags "<p>just <b>some</b> text</p>" "p")
;; => "just <b>some</b> text"
----

[small]#Implemented in: *cljs*#


[[strip-newlines]]
=== _strip-newlines_

Takes a string and replaces newlines with a space. Multiple lines are
replaced with a single space.

[source, clojure]
----
(str/strip-newlines "a\n\nb")
;; => "a b"
----

[small]#Implemented in: *cljs*, *clj*#


[[parse-number]]
=== _parse-number_

General purpose function for parse number like strings to number. It
works with integers and floats.

[source, clojure]
----
(str/parse-number "1.4")
;; => 1

(str/parse-number "1.4" 1)
;; => 1.4

(str/parse-number "1" 2)
;; => 1

(str/parse-number "")
;; => NaN
----

[small]#Implemented in: *cljs*#


[[parse-float]]
=== _parse-float_

Returns a float value. Wraps parseFloat.

[source, clojure]
----
(str/parse-float "1.4")
;; => 1.4

(str/parse-float "1")
;; => 1.0
----

[small]#Implemented in: *cljs*#


[[parse-int]]
=== _parse-int_

Returns a number value in integer form. Wraps parseInt.

[source, clojure]
----
(str/parse-int "1.4")
;; => 1
----

[small]#Implemented in: *cljs*#


[[format]]
=== _format_

Simple string interpolation.

[source, clojure]
----
(str/format "hello %s" "yen")
;; => "hello yen"

(str/format "hello %(name)s" {:name "yen"})
;; => "hello yen"
----

[small]#Implemented in: *cljs*, *clj*#


[[pad]]
=== _pad_

Pads the str with characters until the total string length is equal to
the passed length parameter.

By default, pads on the left with the space char.

[source, clojure]
----
(str/pad "1" {:length 8})
;; => "       1"

(str/pad "1" {:length 8 :padding "0"})
;; => "00000001"

(str/pad "1" {:length 8 :padding "0" :type :right})
;; => "10000000"

(str/pad "1" {:length 8 :padding "0" :type :both})
;; => "00001000"
----

[small]#Implemented in: *cljs*#


[[capitalize]]
=== _capitalize_

Converts first letter of the string to uppercase.

[source, clojure]
----
(str/capitalize "foo")
;; => "Foo"
----

[small]#Implemented in: *cljs*#


[[camelize]]
=== _camelize_

Converts a string from selector-case to camelCase.

[source, clojure]
----
(str/camelize "foo bar")
;; => "fooBar"
----

[small]#Implemented in: *cljs*#


[[dasherize]]
=== _dasherize_

Converts a underscored or camelized string into an dasherized one.

[source, clojure]
----
(str/dasherize "MozTransform")
;; => "-moz-transform"
----

[small]#Implemented in: *cljs*#


[[underscored]]
=== _underscored_

Converts a camelized or dasherized string into an underscored one.

[source, clojure]
----
(str/underscored "MozTransform")
;; => "moz_transform"
----

[small]#Implemented in: *cljs*#


[[titleize]]
=== _titleize_

Converts a string into TitleCase.

[source, clojure]
----
(str/titleize "my name is epeli")
;; => "My Name Is Epeli"
----

[small]#Implemented in: *cljs*#


[[classify]]
=== _classify_

Converts string to camelized class name. First letter is always upper case.

[source, clojure]
----
(str/classify "some_class_name")
;; => "SomeClassName"
----

[small]#Implemented in: *cljs*#


[[humanize]]
=== _humanize_

Converts an underscored, camelized, or dasherized string into a humanized one.

[source, clojure]
----
(str/humanize "  capitalize dash-CamelCase_underscore trim  ")
;; => "Capitalize dash camel case underscore trim"
----

[small]#Implemented in: *cljs*#


[[escape-regexp]]
=== _escape-regexp_

Escape characters on the string that are not safe to use in a RegExp.

[source, clojure]
----
(str/escape-regexp "\s")
;; => "\\s"
----

[small]#Implemented in: *cljs*, *clj*#


== Run tests

_cuerdas_ has splitted implementation for clojure and clojurescript, but tests are build using
speclj and cljx for execute the same tests for both implementations.

For run tests, cljx source should be compiled.

Additional note for run clojurescript tests: you should have instaled phantomjs.

.Compile cljx source, and keep watching changes.
----
$ lein cljx auto
----

.Run tests for clojure and keep watching changes.
----
$ lein spec -a
----

.Compile clojurescript and run test on successful build.
----
$ lein cljsbuild auto dev
----


== How to Contribute?

**cuerdas** unlike Clojure and other Clojure contrib libs, does not have many
restrictions for contributions.

*Pull requests are welcome!*

== License

_cuerdas_ is licensed under BSD (2-Clause) license:

----
Copyright (c) 2014, Andrey Antukh

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
