= cuerdas
Andrey Antukh, <niwi@niwi.nz>
0.8.0
:toc: left
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:
:!numbered:
:idseparator: -
:idprefix:

== Introduction

The missing clojure(script) string manipulation library.

[quote, Federico García Lorca, Las Seis Cuerdas]
____
La guitarra, +
hace llorar a los sueños. +
El sollozo de las almas +
perdidas, +
se escapa por su boca +
redonda. +
Y como la tarántula +
teje una gran estrella +
para cazar suspiros, +
que flotan en su negro +
aljibe de madera.
____


== Install

The simplest way to use _cuerdas_ in a clojure project, is by including it in the dependency
vector on your *_project.clj_* file:

[source,clojure]
----
[funcool/cuerdas "0.8.0"]
----


== Quick start

.Import the namespace
[source, clojure]
----
(ns my.namespace
  (:require [cuerdas.core :as str]))
----

.Use its functions
[source, clojure]
----
(str/strip-tags "<p>just <b>some</b> text</p>")
;; => "just some text"

(str/strip-tags "<p>just <b>some</b> text</p>" ["p"])
;; => "just <b>some</b> text"
----


== Reference

=== contains?

Determines whether a string contains a substring.

[source, clojure]
----
(str/contains? "foobar" "bar")
;; => true

(str/contains? "foobar" nil)
;; => false

(str/contains? nil nil)
;; => false
----

=== starts-with?

Check if the string starts with prefix.

Alias: startswith?

[source, clojure]
----
(str/starts-with? "foobar" "foo")
;; => true

(str/starts-with? "foobar" nil)
;; => false

(str/starts-with? nil "foo")
;; => false
----


=== ends-with?

Check if the string ends with suffix.

Alias: endswith?

[source, clojure]
----
(str/ends-with? "foobar" "bar")
;; => true

(str/ends-with? "foobar" nil)
;; => false

(str/ends-with? nil "bar")
;; => false
----


=== empty?

Check if the string is empty.

[source, clojure]
----
(str/empty? "foobar")
;; => false

(str/empty? nil)
;; => true

(str/empty? "")
;; => true

(str/empty? " ")
;; => false
----


=== blank?

Check if the string is empty or contains only whitespaces.

[source, clojure]
----
(str/blank? "foobar")
;; => false

(str/blank? "   ")
;; => true

(str/blank? "")
;; => true

(str/blank? nil)
;; => true
----


=== alpha?

Checks if a string contains only alpha characters.

[source, clojure]
----
(str/alpha? nil)
;; => false

(str/alpha? " ")
;; => false

(str/alpha? "Test")
;; => true
----


=== numeric?

Checks if a string contains only numeric characters.

[source, clojure]
----
(str/numeric? nil)
;; => false

(str/numeric? "1.1")
;; => false

(str/numeric? "0123")
;; => true
----


=== alpha-numeric?

Checks if a string contains only alphanumeric characters.

[source, clojure]
----
(str/alpha-numeric? nil)
;; => false

(str/alpha-numeric? "")
;; => false

(str/alpha-numeric? "Test123")
;; => true
----


=== upper

Convert a string to all upper-case.

[source, clojure]
----
(str/upper "foobar")
;; => "FOOBAR"

(str/upper nil)
;; => nil
----


=== lower

Convert a string to all lower-case.

[source, clojure]
----
(str/lower "FOO")
;; => "foo"

(str/lower nil)
;; => nil
----

=== repeat

Repeats string N times.

[source, clojure]
----
(str/repeat "a" 3)
;; => "aaa"

(str/repeat nil 3)
;; => nil
----


=== trim

Removes whitespace or specified characters from
both ends of string.

Alias: _strip_

[source, clojure]
----
(str/trim " foo ")
;; => "foo"

(str/trim "-foo-", "-")
;; => "foo"

(str/trim nil)
;; => nil
----


=== ltrim

Removes whitespace or specified characters from
left side of string.

Alias: _lstrip_

[source, clojure]
----
(str/ltrim " foo ")
;; => "foo "

(str/ltrim "-foo-", "-")
;; => "foo-"

(str/ltrim nil)
;; => nil
----


=== rtrim

Removes whitespace or specified characters from
right side of string.

Alias: _rstrip_

[source, clojure]
----
(str/rtrim " foo ")
;; => " foo"

(str/rtrim "-foo-", "-")
;; => "-foo"

(str/rtrim nil)
;; => nil
----


=== strip-prefix

Remove prefix from string if it matches exactly or leave
the string untouched.

[source, clojure]
----
(str/strip-prefix nil nil)
;; => nil

(str/strip-prefix "a" nil)
;; => "a"

(str/strip-prefix "-=a" "-=")
;; => "a"
----


=== strip-suffix

Remove suffix from string if it matches exactly or leave
the string untouched.

[source, clojure]
----
(str/strip-suffix nil nil)
;; => nil

(str/strip-suffix "a" nil)
;; => "a"

(str/strip-suffix "a=-" "=-")
;; => "a"
----


=== collapse-whitespace

Converts any adjacent whitespace characters to a single space.

[source, clojure]
----
(str/collapse-whitespace "a\n\nb")
;; => "a b"

(str/collapse-whitespace nil)
;; => nil
----


=== prune

Truncates a string to certain left and adds "..." if necesary. Making
sure that the pruned string does not exceed the original length and avoid
half-chopped words when truncating.

[source, clojure]
----
(str/prune "Hello World" 5)
;; => "Hello..."

(str/prune "Hello World" 8)
;; => "Hello..."

(str/prune "Hello World" 11 " (...)")
;; => "Hello (...)"

(str/prune nil 5)
;; => nil
----


=== join

Join strings together with given separator.

[source, clojure]
----
(str/join ["foo" "bar"])
;; => "foobar"

(str/join "," ["foo" "bar"])
;; => "foo,bar"
----


=== split

Splits a string on a separator a limited number of times.
The separator can be a string or RegExp instance.

[source, clojure]
----
(str/split "1 2 3")
;; => ["1" "2" "3"]

(str/split "1 2 3" " ")
;; => ["1" "2" "3"])

(str/split "1 2 3" #"\s")
;; => ["1" "2" "3"]

(str/split "1 2 3" #"\s" 2)
;; => ["1" "2 3"]

(str/split nil)
;; => nil
----


=== reverse

Return strign reverted

[source, clojure]
----
(str/reverse "bar")
;; => "rab"

(str/reverse nil)
;; => nil
----


=== chars

Returns a seq of char strings from string.

[source, clojure]
----
(str/chars "bar")
;; => ["b" "a" "r"]

(str/chars nil)
;; => nil
----


=== lines

Return a list of the lines in the string.

[source, clojure]
----
(str/lines "foo\nbar")
;; => ["foo" "bar"]

(str/lines nil)
;; => nil
----


=== unlines

Joins a list of strings with a newline separator.  This operation is
the opposite of lines.

[source, clojure]
----
(str/unlines ["foo" "nbar"])
;; => "foo\nbar"

(str/unlines nil)
;; => nil
----


=== words

Returns a vector of the words in the string. Can be provided with a regular
expression that matches a single word (defaults to `[a-zA-Z0-9_-]+`).

[source, clojure]
----
(str/words "foo, bar")
;; => ["foo" "bar"]

(str/words nil)
;; => nil

(str/words "foo, bar." #"[^, ]")
;; => ["foo" "bar."]
----


=== slice

Extracts a section of a string and returns a new string.

[source, clojure]
----
(str/slice "123" 1)
;; => "23"

(str/slice "1234" 1 3)
;; => "23"

(str/slice nil 1 3)
;; => nil
----


=== replace

Replaces all instance of match with replacement in s.

[source, clojure]
----
(str/replace "aa bb aa" "aa" "kk")
;; => "kk bb kk"

(str/replace "aa bb aa" #"aa" "kk")
;; => "kk bb kk"

(str/replace nil #"aa" "kk")
;; => nil
----


=== replace-first

Replaces first instance of match with replacement in s.

[source, clojure]
----
(str/replace-first "aa bb aa" "aa" "kk")
;; => "kk bb aa"

(str/replace-first "aa bb aa" #"aa" "kk")
;; => "kk bb aa"

(str/replace-first nil #"aa" "kk")
;; => nil
----


=== surround

Surround a string with another string.

[source, clojure]
----
(str/surround "a" "-")
;; => "-a-"

(str/surround "a" "-^-")
;; => "-^-a-^-"

(str/surround nil "-^-")
;; => nil
----


=== unsurround

Unsurround a string surrounded by another.

[source, clojure]
----
(str/unsurround "-a-" "-")
;; => "a"

(str/unsurround "-^-a-^-" "-^-")
;; => "a"

(str/unsurround nil "-")
;; => nil
----


=== quote

Quote a string.

[source, clojure]
----
(str/quote "a")
;; => "\"a\""

(str/quote nil)
;; => nil
----


=== unquote

Unquote a string.

[source, clojure]
----
(str/unquote "\"a\"")
;; => "a"

(str/unquote nil)
;; => nil
----


=== strip-tags

Remove html tags from string.

[source, clojure]
----
(str/strip-tags "<p>just <b>some</b> text</p>")
;; => "just some text"

(str/strip-tags "<p>just <b>some</b> text</p>" ["p"])
;; => "just <b>some</b> text"

(str/strip-tags nil)
;; => nil
----

It also allows arbitrary replacements:

[source, clojure]
----
(str/strip-tags "<p>just<br>text</p>" {:br "\n"})
;; => "just\ntext"

(str/strip-tags "<p>just<br>text</p>" ["br"] {:br "\n"})
;; => "<p>just\ntext</p>"
----

=== clean

Trim and replace multiple spaces with a single space.

[source, clojure]
----
(str/clean "  a   b   ")
;; => "a b"

(str/clean nil)
;; => nil
----


=== strip-newlines

Takes a string and replaces newlines with a space. Multiple lines are
replaced with a single space.

[source, clojure]
----
(str/strip-newlines "a\n\nb")
;; => "a b"

(str/strip-newlines nil)
;; => nil
----


=== parse-number

General purpose function for parse number like strings to number. It
works with integers and floats.

[source, clojure]
----
(str/parse-number "1.4")
;; => 1

(str/parse-number "1.4" 1)
;; => 1.4

(str/parse-number "1" 2)
;; => 1

(str/parse-number "")
;; => NaN
----

WARNING: only on *clojurescript*


=== parse-float

Returns a float value. Wraps parseFloat.

[source, clojure]
----
(str/parse-float "1.4")
;; => 1.4

(str/parse-float "1")
;; => 1.0

(str/parse-float nil)
;; => NaN
----

WARNING: only on *clojurescript*


=== parse-int

Returns a number value in integer form. Wraps parseInt.

[source, clojure]
----
(str/parse-int "1.4")
;; => 1

(str/parse-int nil)
;; => NaN
----

WARNING: only on *clojurescript*


=== parse-double

Returns a number value in integer form. Wraps parseInt.

[source, clojure]
----
(str/parse-double "1.4")
;; => 1.4

(str/parse-double nil)
;; => NaN
----

WARNING: only on *clojure*


=== parse-long

Returns a number value in integer form. Wraps parseInt.

[source, clojure]
----
(str/parse-long "1.4")
;; => 1

(str/parse-long nil)
;; => NaN
----

WARNING: only on *clojure*


=== to-bool

Returns true for 1/on/true/yes string values (case-insensitive), false otherwise.

[source, clojure]
----
(str/to-bool "hello")
;; => false

(str/to-bool "on")
;; => true
----


=== format

Simple string formatting function.

The string formating works in two main modes: indexed and associative.

The indexed mode is the most simple and consists in using `%s` tokens in the string
indicating the position where interpolation should be done and an arbitrary number
of non associate arguments. Format will replace all `%s` occurences with the
provided values in ordered mode:

[source, clojure]
----
(str/format "hello %s and %s" "yen" "ciri")
;; => "hello yen and ciri"
----

If you don't provide enough values, the `%s` tokens will be keeped intouched:

[source, clojure]
----
(str/format "hello %s and %s" "yen")
;; "hello yen and %s"
----

There are also the associative mode that consists in passing only one associative
argument (map or vector) and use named interpolation tokens:

[source, clojure]
----
(str/format "hello %(name)s" {:name "yen"})
;; => "hello yen"
----

A part of the `%()s` syntax, the `$something` can be used:

[source, clojure]
----
(str/format "hello $name" {:name "yen"})
;; => "hello yen"
----

And you can access to indexed positions of an vector using `$0`, `$1`, `$N` syntax:

[source, clojure]
----
(str/format "hello $0" ["yen"])
;; => "hello yen"
----


=== pad

Pads the str with characters until the total string length is equal to
the passed length parameter.

By default, pads on the left with the space char.

[source, clojure]
----
(str/pad "1" {:length 8})
;; => "       1"

(str/pad nil {:length 8})
;; => nil

(str/pad "1" {:length 8 :padding "0"})
;; => "00000001"

(str/pad "1" {:length 8 :padding "0" :type :right})
;; => "10000000"

(str/pad "1" {:length 8 :padding "0" :type :both})
;; => "00001000"
----


=== slug

Transforms string or keyword into URL slug.

[source, clojure]
----
(str/slug "Un éléphant à l'orée du bois")
;; => "un-elephant-a-loree-du-bois"

(str/slug nil)
;; => nil
----


=== capitalize

Uppercases the first character of a string.

[source, clojure]
----
(str/capitalize "foo")
;; => "Foo"

(str/capitalize nil)
;; => nil
----


=== camel

Convert a string or keyword to a camelCased string.

[source, clojure]
----
(str/camel "foo bar")
;; => "fooBar"

(str/camel :foo_barBaz)
;; => "fooBarBaz"

(str/camel nil)
;; => nil
----


=== kebab

Convert a string or keyword into a kebab-cased-string.

[source, clojure]
----
(str/kebab "Favorite BBQ food")
;; => "favorite-bbq-food"

(str/kebab :favorite-bbq-food)
;; => "favorite-bbq-food"

(str/kebab nil)
;; => nil
----


=== snake

Convert a string or keyword to a snake_cased_string.

[source, clojure]
----
(str/snake "Slither-sliter Slither")
;; => "slither_slither_slither"

(str/snake :slither-slither)
;; => "slither_slither"

(str/snake nil)
;; => nil
----


=== pascal

Convert a string or keyword into a PascalCasedString
(aka, UpperCamelCase and ClassCase).

[source, clojure]
----
(str/pascal "my name is epeli")
;; => "MyNameIsEpeli"

(str/pascal :some-record)
;; => "SomeRecord"

(str/pascal nil)
;; => nil
----


=== human

Convert a string or keyword to a human friendly string
(lower case and spaces).

[source, clojure]
----
(str/human "JustNiceForReading")
;; => "just nice for reading"

(str/human :great-for-csv-headers
;; => "great for csv headers"

(str/human nil)
;; => nil
----

=== title

Convert a string or keyword into a space separated string
with each word capitalized.

[source, clojure]
----
(str/title "a tale of two cities")
;; => "A Tale Of Two Cities"

(str/title :title-case
;; => "Title Case"

(str/title nil)
;; => nil
----

=== phrase

Convert a potentially mixed string or keyword into a
capitalized, spaced string

[source, clojure]
----
(str/phrase "  capitalize dash-CamelCase_underscore trim  ")
;; => "Capitalize dash camel case underscore trim"

(str/phrase :nobody-uses-keywords-this-long-but-it-still-works
;; => "Nobody uses keywords this long but it still works"

(str/phrase nil)
;; => nil
----


=== css-selector

Convert a JavaScript style selector to CSS style selector

[source, clojure]
----
(str/css-selector "PrependedWithDash")
;; => "-prepended-with-dash"

(str/css-selector "noPrependedWithDash")
;; => "no-prepended-with-dash"

(str/css-selector nil)
;; => nil
----


=== js-selector

Convert a CSS style selector to JavaScript style selector.

[source, clojure]
----
(str/js-selector "-pascal-case-me")
;; => "PascalCaseMe"

(str/js-selector "camel-case-me")
;; => "camelCaseMe"

(str/js-selector nil)
;; => nil
----


=== keyword

A more helpful and forigiving version of `clojure.core/keyword`.

[source, clojure]
----
(str/keyword "just_doIt Right")
;; => :just-do-it-right

(str/keyword "foo" "auto namespace me")
;; => :foo/auto-namespace-me

;; and assuming the user namespace
(str/keyword *ns* "auto namespace me")
;; => :user/auto-namespace-me

(str/keyword nil)
;; => nil
----


=== escape-regexp

Escape characters on the string that are not safe to use in a RegExp.

[source, clojure]
----
(str/escape-regexp "\s")
;; => "\\s"
----


=== <<

Unindent lines. Either strip preceeding whitespace automatically or
with a user supplied regex.

[source, clojure]
----
(str/<< "first line

           second line (indented)

         another line")
----

yields the string

----
first line

  second line (indented)

another line
----


== Run tests

_cuerdas_ has targeted some parts of implementation for Clojure and
ClojureScript using Reader Conditionals.

.Run tests in the Clojure environment using Leiningen.
----
$ lein test cuerdas.core-tests
----

.Compile ClojureScript to JavaScript.
----
$ ./scripts/build
----

.Run tests on compiled ClojureScript using node.
----
$ node ./out/tests.js
----


== How to Contribute?

**cuerdas**' source is on https://github.com/funcool/cuerdas[github].

Unlike Clojure and other Clojure contrib libs, cuerdas does not have many
restrictions for contributions.

*Pull requests are welcome!*


== License

_cuerdas_ is licensed under BSD (2-Clause) license:

----
Copyright (c) 2014-2015 Andrey Antukh <niwi@niwi.nz>

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
