#!/usr/bin/env sh

set -eu

prefix_dir=${1:-}

if [ -z "$prefix_dir" ]; then
   echo "Must pass prefix dir as first parameter"
   exit 1
fi

bin_dir="$prefix_dir/bin"
lumo_bin="$bin_dir/lumo"

if [ ! -x "$lumo_bin" ]; then
    tmp_dir=$(mktemp -d /tmp/lumo.XXXXXXXXXX) || { echo "Failed to create temp file"; exit 2; }
    zip_path="$tmp_dir/lumo.zip"
    curl -fsSJLo "$zip_path" https://github.com/anmonteiro/lumo/releases/download/1.8.0/lumo_linux64.zip
    unzip -vp "$zip_path" lumo > "$lumo_bin"
    chmod +x "$lumo_bin"
    echo "Installed Lumo in $bin_dir"
else
    echo "Not installing Lumo, already in $bin_dir"
fi
